on:
  push:
    paths:
      - "vscode-ext/**"

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: cd vscode-ext && npm i
      # - name: Publish to Open VSX Registry
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          packagePath: ./vscode-ext
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
      # - name: Publish to Visual Studio Marketplace (manually)
      #   env:
      #     secret: ${{ secrets.VS_MARKETPLACE_TOKEN }}
      #   run: cd vscode-ext && npm install -g @vscode/vsce && vsce publish -p "$secret"